In [1]:
import pandas as pd
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Paris', 'London']
})
print(df)


      Name  Age      City
0    Alice   25  New York
1      Bob   30     Paris
2  Charlie   35    London


In [2]:
a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)

0    1
1    7
2    2
dtype: int64


In [3]:
print(myvar[0])

1


In [4]:
print(df.loc[[0, 1]])

    Name  Age      City
0  Alice   25  New York
1    Bob   30     Paris


In [5]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr)


[1 2 3]


In [6]:
arr2d = np.array([[1, 2], [3, 4]])
print(arr2d)


[[1 2]
 [3 4]]


In [7]:
print(arr.shape)   # Shape of array
print(arr.ndim)    # Number of dimensions
print(arr.dtype)   # Data type


(3,)
1
int32


In [8]:
a = np.array([10, 20, 30, 40])
print(a[1])        # 20
print(a[1:3])      # [20 30]


20
[20 30]


In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)     # [5 7 9]
print(a * b)     # [4 10 18]
print(a ** 2)    # [1 4 9]
print(np.sqrt(b))  # [2. 2.236 2.449]


[5 7 9]
[ 4 10 18]
[1 4 9]
[2.         2.23606798 2.44948974]


In [11]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a)   # [1 2 3]
print(b)   # [100 2 3]


[1 2 3]
[100   2   3]
